-- Retroactively synchronize custom warchief titles.
-- Title IDs 9009 (Warchief) and 9010 (Ex-Warchief) must use these MaskID values
-- in CharTitles.dbc for the knownTitles bit updates below.
-- Ex-Warchief has been verified from a known-good row as knownTitles field 4, bit 24
-- (0 0 0 0 16777216 0), which is MaskID 152; Warchief is the preceding MaskID.
SET @WARCHIEF_TITLE_MASK_ID := 151;
SET @FORMER_WARCHIEF_TITLE_MASK_ID := 152;
-- A previous version of this backfill used the title IDs as if their MaskID values were 178/179.
-- Clear those bad bits for the affected characters so re-running this file repairs that state.
SET @BAD_WARCHIEF_TITLE_MASK_ID := 178;
SET @BAD_FORMER_WARCHIEF_TITLE_MASK_ID := 179;
SET @WARCHIEF_MOUNT_SPELL := 16084;
SET @CURRENT_WARCHIEF_NAME := 'tijuana';

SET @WARCHIEF_TITLE_FIELD := FLOOR(@WARCHIEF_TITLE_MASK_ID / 32);
SET @WARCHIEF_TITLE_FLAG := 1 << (@WARCHIEF_TITLE_MASK_ID % 32);
SET @FORMER_WARCHIEF_TITLE_FIELD := FLOOR(@FORMER_WARCHIEF_TITLE_MASK_ID / 32);
SET @FORMER_WARCHIEF_TITLE_FLAG := 1 << (@FORMER_WARCHIEF_TITLE_MASK_ID % 32);
SET @BAD_WARCHIEF_TITLE_FIELD := FLOOR(@BAD_WARCHIEF_TITLE_MASK_ID / 32);
SET @BAD_WARCHIEF_TITLE_FLAG := 1 << (@BAD_WARCHIEF_TITLE_MASK_ID % 32);
SET @BAD_FORMER_WARCHIEF_TITLE_FIELD := FLOOR(@BAD_FORMER_WARCHIEF_TITLE_MASK_ID / 32);
SET @BAD_FORMER_WARCHIEF_TITLE_FLAG := 1 << (@BAD_FORMER_WARCHIEF_TITLE_MASK_ID % 32);

DROP TEMPORARY TABLE IF EXISTS `warchief_title_backfill`;
CREATE TEMPORARY TABLE `warchief_title_backfill` (
  `guid` INT UNSIGNED NOT NULL PRIMARY KEY,
  `title0` INT UNSIGNED NOT NULL DEFAULT 0,
  `title1` INT UNSIGNED NOT NULL DEFAULT 0,
  `title2` INT UNSIGNED NOT NULL DEFAULT 0,
  `title3` INT UNSIGNED NOT NULL DEFAULT 0,
  `title4` INT UNSIGNED NOT NULL DEFAULT 0,
  `title5` INT UNSIGNED NOT NULL DEFAULT 0,
  `chosenTitle` INT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=MEMORY;

INSERT INTO `warchief_title_backfill` (`guid`, `title0`, `title1`, `title2`, `title3`, `title4`, `title5`, `chosenTitle`)
SELECT
  `guid`,
  CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(CONCAT(COALESCE(NULLIF(TRIM(`knownTitles`), ''), '0 0 0 0 0 0'), ' 0 0 0 0 0 0'), ' ', 1), ' ', -1) AS UNSIGNED),
  CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(CONCAT(COALESCE(NULLIF(TRIM(`knownTitles`), ''), '0 0 0 0 0 0'), ' 0 0 0 0 0 0'), ' ', 2), ' ', -1) AS UNSIGNED),
  CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(CONCAT(COALESCE(NULLIF(TRIM(`knownTitles`), ''), '0 0 0 0 0 0'), ' 0 0 0 0 0 0'), ' ', 3), ' ', -1) AS UNSIGNED),
  CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(CONCAT(COALESCE(NULLIF(TRIM(`knownTitles`), ''), '0 0 0 0 0 0'), ' 0 0 0 0 0 0'), ' ', 4), ' ', -1) AS UNSIGNED),
  CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(CONCAT(COALESCE(NULLIF(TRIM(`knownTitles`), ''), '0 0 0 0 0 0'), ' 0 0 0 0 0 0'), ' ', 5), ' ', -1) AS UNSIGNED),
  CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(CONCAT(COALESCE(NULLIF(TRIM(`knownTitles`), ''), '0 0 0 0 0 0'), ' 0 0 0 0 0 0'), ' ', 6), ' ', -1) AS UNSIGNED),
  `chosenTitle`
FROM `characters`
WHERE `guid` IN (SELECT `guid` FROM `character_spell` WHERE `spell` = @WARCHIEF_MOUNT_SPELL)
   OR LOWER(`name`) = LOWER(@CURRENT_WARCHIEF_NAME);

-- Everyone who knows the mount spell becomes an Ex-Warchief and loses the current Warchief title.
UPDATE `warchief_title_backfill` bt
INNER JOIN `character_spell` cs ON cs.`guid` = bt.`guid` AND cs.`spell` = @WARCHIEF_MOUNT_SPELL
SET
  bt.`title0` = ((bt.`title0` | IF(@FORMER_WARCHIEF_TITLE_FIELD = 0, @FORMER_WARCHIEF_TITLE_FLAG, 0)) & ~IF(@WARCHIEF_TITLE_FIELD = 0, @WARCHIEF_TITLE_FLAG, 0) & ~IF(@BAD_WARCHIEF_TITLE_FIELD = 0, @BAD_WARCHIEF_TITLE_FLAG, 0) & ~IF(@BAD_FORMER_WARCHIEF_TITLE_FIELD = 0, @BAD_FORMER_WARCHIEF_TITLE_FLAG, 0)),
  bt.`title1` = ((bt.`title1` | IF(@FORMER_WARCHIEF_TITLE_FIELD = 1, @FORMER_WARCHIEF_TITLE_FLAG, 0)) & ~IF(@WARCHIEF_TITLE_FIELD = 1, @WARCHIEF_TITLE_FLAG, 0) & ~IF(@BAD_WARCHIEF_TITLE_FIELD = 1, @BAD_WARCHIEF_TITLE_FLAG, 0) & ~IF(@BAD_FORMER_WARCHIEF_TITLE_FIELD = 1, @BAD_FORMER_WARCHIEF_TITLE_FLAG, 0)),
  bt.`title2` = ((bt.`title2` | IF(@FORMER_WARCHIEF_TITLE_FIELD = 2, @FORMER_WARCHIEF_TITLE_FLAG, 0)) & ~IF(@WARCHIEF_TITLE_FIELD = 2, @WARCHIEF_TITLE_FLAG, 0) & ~IF(@BAD_WARCHIEF_TITLE_FIELD = 2, @BAD_WARCHIEF_TITLE_FLAG, 0) & ~IF(@BAD_FORMER_WARCHIEF_TITLE_FIELD = 2, @BAD_FORMER_WARCHIEF_TITLE_FLAG, 0)),
  bt.`title3` = ((bt.`title3` | IF(@FORMER_WARCHIEF_TITLE_FIELD = 3, @FORMER_WARCHIEF_TITLE_FLAG, 0)) & ~IF(@WARCHIEF_TITLE_FIELD = 3, @WARCHIEF_TITLE_FLAG, 0) & ~IF(@BAD_WARCHIEF_TITLE_FIELD = 3, @BAD_WARCHIEF_TITLE_FLAG, 0) & ~IF(@BAD_FORMER_WARCHIEF_TITLE_FIELD = 3, @BAD_FORMER_WARCHIEF_TITLE_FLAG, 0)),
  bt.`title4` = ((bt.`title4` | IF(@FORMER_WARCHIEF_TITLE_FIELD = 4, @FORMER_WARCHIEF_TITLE_FLAG, 0)) & ~IF(@WARCHIEF_TITLE_FIELD = 4, @WARCHIEF_TITLE_FLAG, 0) & ~IF(@BAD_WARCHIEF_TITLE_FIELD = 4, @BAD_WARCHIEF_TITLE_FLAG, 0) & ~IF(@BAD_FORMER_WARCHIEF_TITLE_FIELD = 4, @BAD_FORMER_WARCHIEF_TITLE_FLAG, 0)),
  bt.`title5` = ((bt.`title5` | IF(@FORMER_WARCHIEF_TITLE_FIELD = 5, @FORMER_WARCHIEF_TITLE_FLAG, 0)) & ~IF(@WARCHIEF_TITLE_FIELD = 5, @WARCHIEF_TITLE_FLAG, 0) & ~IF(@BAD_WARCHIEF_TITLE_FIELD = 5, @BAD_WARCHIEF_TITLE_FLAG, 0) & ~IF(@BAD_FORMER_WARCHIEF_TITLE_FIELD = 5, @BAD_FORMER_WARCHIEF_TITLE_FLAG, 0)),
  bt.`chosenTitle` = CASE WHEN bt.`chosenTitle` IN (@WARCHIEF_TITLE_MASK_ID, @BAD_WARCHIEF_TITLE_MASK_ID, @BAD_FORMER_WARCHIEF_TITLE_MASK_ID) THEN 0 ELSE bt.`chosenTitle` END;

-- The current Warchief keeps/receives Warchief and loses Ex-Warchief.
UPDATE `warchief_title_backfill` bt
INNER JOIN `characters` c ON c.`guid` = bt.`guid` AND LOWER(c.`name`) = LOWER(@CURRENT_WARCHIEF_NAME)
SET
  bt.`title0` = ((bt.`title0` | IF(@WARCHIEF_TITLE_FIELD = 0, @WARCHIEF_TITLE_FLAG, 0)) & ~IF(@FORMER_WARCHIEF_TITLE_FIELD = 0, @FORMER_WARCHIEF_TITLE_FLAG, 0) & ~IF(@BAD_WARCHIEF_TITLE_FIELD = 0, @BAD_WARCHIEF_TITLE_FLAG, 0) & ~IF(@BAD_FORMER_WARCHIEF_TITLE_FIELD = 0, @BAD_FORMER_WARCHIEF_TITLE_FLAG, 0)),
  bt.`title1` = ((bt.`title1` | IF(@WARCHIEF_TITLE_FIELD = 1, @WARCHIEF_TITLE_FLAG, 0)) & ~IF(@FORMER_WARCHIEF_TITLE_FIELD = 1, @FORMER_WARCHIEF_TITLE_FLAG, 0) & ~IF(@BAD_WARCHIEF_TITLE_FIELD = 1, @BAD_WARCHIEF_TITLE_FLAG, 0) & ~IF(@BAD_FORMER_WARCHIEF_TITLE_FIELD = 1, @BAD_FORMER_WARCHIEF_TITLE_FLAG, 0)),
  bt.`title2` = ((bt.`title2` | IF(@WARCHIEF_TITLE_FIELD = 2, @WARCHIEF_TITLE_FLAG, 0)) & ~IF(@FORMER_WARCHIEF_TITLE_FIELD = 2, @FORMER_WARCHIEF_TITLE_FLAG, 0) & ~IF(@BAD_WARCHIEF_TITLE_FIELD = 2, @BAD_WARCHIEF_TITLE_FLAG, 0) & ~IF(@BAD_FORMER_WARCHIEF_TITLE_FIELD = 2, @BAD_FORMER_WARCHIEF_TITLE_FLAG, 0)),
  bt.`title3` = ((bt.`title3` | IF(@WARCHIEF_TITLE_FIELD = 3, @WARCHIEF_TITLE_FLAG, 0)) & ~IF(@FORMER_WARCHIEF_TITLE_FIELD = 3, @FORMER_WARCHIEF_TITLE_FLAG, 0) & ~IF(@BAD_WARCHIEF_TITLE_FIELD = 3, @BAD_WARCHIEF_TITLE_FLAG, 0) & ~IF(@BAD_FORMER_WARCHIEF_TITLE_FIELD = 3, @BAD_FORMER_WARCHIEF_TITLE_FLAG, 0)),
  bt.`title4` = ((bt.`title4` | IF(@WARCHIEF_TITLE_FIELD = 4, @WARCHIEF_TITLE_FLAG, 0)) & ~IF(@FORMER_WARCHIEF_TITLE_FIELD = 4, @FORMER_WARCHIEF_TITLE_FLAG, 0) & ~IF(@BAD_WARCHIEF_TITLE_FIELD = 4, @BAD_WARCHIEF_TITLE_FLAG, 0) & ~IF(@BAD_FORMER_WARCHIEF_TITLE_FIELD = 4, @BAD_FORMER_WARCHIEF_TITLE_FLAG, 0)),
  bt.`title5` = ((bt.`title5` | IF(@WARCHIEF_TITLE_FIELD = 5, @WARCHIEF_TITLE_FLAG, 0)) & ~IF(@FORMER_WARCHIEF_TITLE_FIELD = 5, @FORMER_WARCHIEF_TITLE_FLAG, 0) & ~IF(@BAD_WARCHIEF_TITLE_FIELD = 5, @BAD_WARCHIEF_TITLE_FLAG, 0) & ~IF(@BAD_FORMER_WARCHIEF_TITLE_FIELD = 5, @BAD_FORMER_WARCHIEF_TITLE_FLAG, 0)),
  bt.`chosenTitle` = CASE WHEN bt.`chosenTitle` IN (@FORMER_WARCHIEF_TITLE_MASK_ID, @BAD_WARCHIEF_TITLE_MASK_ID, @BAD_FORMER_WARCHIEF_TITLE_MASK_ID) THEN 0 ELSE bt.`chosenTitle` END;

UPDATE `characters` c
INNER JOIN `warchief_title_backfill` bt ON bt.`guid` = c.`guid`
SET c.`knownTitles` = CONCAT(bt.`title0`, ' ', bt.`title1`, ' ', bt.`title2`, ' ', bt.`title3`, ' ', bt.`title4`, ' ', bt.`title5`, ' '),
    c.`chosenTitle` = bt.`chosenTitle`;

DROP TEMPORARY TABLE IF EXISTS `warchief_title_backfill`;
