"""Generate the DBC-mirror and world-DB scripts for the ported arenas.

Hand-writing these would be 14 map rows, 14 battlemaster rows, 224 PvP difficulty
rows, 28 start locations, 28 world-state rows and 14 templates. Generating them
keeps the ids arithmetic instead of typed, and keeps this file as the one place
a coordinate is corrected.

Run:  python gen_arena_sql.py
Writes into sql/custom/dbc/ and sql/custom/world/.

Coordinates
-----------
centre_x / centre_y / floor_z were measured from the client terrain by
adt_probe.py + wmo_floor.py, not surveyed in-game. The method was validated
against the two arenas already live: Tol'viron's measured centre lands 1.2 yards
from the midpoint of its real start locations and its floor within 1.7 yards.

`confidence` records how good the evidence is per arena:
  high   - a collision volume, gate doodads or arena pillars fixed the position
  medium - the arena's own WMO mesh, which the two validations agree with
  low    - no arena-shaped object could be identified; this is the centre of the
           most plausible structure and WILL need .gps confirmation

Start positions live in WorldSafeLocs and gates in battleground_custom_arena_object,
both server-side tables, so correcting any of this is an UPDATE plus
`.reload battleground_template` -- never a rebuild and never a client patch.
"""

import os

OUT_DBC = r"C:\Projects\Gamedev\wow\servers\tc-lplus\sql\custom\dbc"
OUT_WORLD = r"C:\Projects\Gamedev\wow\servers\tc-lplus\sql\custom\world"
STAMP = "2026_08_06_02"

# id blocks, chosen clear of everything currently in use (checked against the
# live dbc schema). AreaTable is deliberately absent -- see the header note in
# the generated DBC file.
WSL_BASE = 52600        # WorldSafeLocs, 2 per arena
PVPDIFF_BASE = 93000    # PvpDifficulty, 16 per arena
WSUI_BASE = 90100       # WorldStateUI, 2 per arena

DOOR_GO = 179469        # "Arena Door", the stock arena gate
DOOR_OFFSET = 45.0      # gates, along X from centre
SPAWN_OFFSET = 57.0     # players start behind their gate
SPAWN_Z_LIFT = 2.0      # measured floors are the mesh; stand slightly above it

LANG_MASK = 16712190
DESC_MASK = 16712188

# bg_type_id, map_id, directory, display name, centre x, centre y, floor z, confidence, evidence
ARENAS = [
    (872,  982, "coliseumarena",      "Coliseum of Past Echoes",        8077.39, -2749.79, 1242.32, "low",    "PVP_TITAN_ARENA.WMO; floor sits outside the placement bbox, so treat Z as provisional"),
    (873,  983, "nerubianarena",      "Imperial Arena of Thakraj",       544.03,  -909.11,   85.22, "medium", "NERUBIAN_ARENA.WMO mesh"),
    (874,  984, "maldraxxuscoliseum", "Maldraxxus Coliseum",            2833.00,  2253.00, 3260.30, "high",   "9NC_MALDRAXXUSARENA_LARGEPILLAR M2 bases ring this point at Z 3260.2-3260.4"),
    (875,  985, "nagrandarena2",      "Nagrand Arena (Remastered)",    -2043.54,  6654.35,   70.94, "medium", "7NG_NAGRANDARENA_PVPSTADIUM.WMO mesh"),
    (876,  986, "bladesedgearena2b",  "Blade's Edge Arena (Remastered)",2785.61,  6066.08,   84.13, "medium", "7OG_BLADESEDGEARENA_PVPSTADIUM.WMO mesh"),
    (877, 1007, "karazhanarena",      "Guardian's Hall",                 536.49,   805.68,   64.25, "medium", "KARAZHAN_ARENA.WMO, the map's only WMO"),
    (878, 1008, "ulduararena",        "Spark of Creator",                533.42,   800.12,  131.40, "medium", "ULDUAR_ARENA.WMO, the map's only WMO"),
    (879, 1401, "BaradinHoldArena",   "Baradin Hold Arena",            -1232.87,   981.33,  119.58, "low",    "no arena-named WMO; TB_TOWER is the closest structure to the tile centre and the densest doodad cluster"),
    (880, 1402, "obeliskofthestarts", "Obelisk of the Stars",          -9261.33, -1550.22,  100.44, "high",   "14 PVP_COLLISIONPANE WMOs fence a 43x34 yard box; Z is the pane base"),
    (881, 1403, "thetwistingnether",  "The Twisting Nether",            4500.37, -1273.10,  386.80, "high",   "two 7DU_TOMBOFSARGERAS_FIREDOOR01 gates at Z 386.7/386.8 either side of centre"),
    (882, 1504, "BlackrookHoldArena", "Black Rook Hold Arena",          1458.69,  1458.06,  247.18, "medium", "7VS_BLACKROOKHOLD_ARENA.WMO mesh"),
    (883, 1552, "valsharaharena",     "Ashamane's Fall",                3548.97,  5542.23,  378.48, "medium", "CUSTOM_VALSHARAH_ARENA.WMO mesh"),
    (884, 1683, "ulduaroutarena",     "The Inventor's Library",         8859.22,  -904.74,  884.09, "low",    "no arena-named WMO; ULDUAR_EXT03 origin used as a placeholder"),
    (885, 1684, "gundrakarena",       "Amphitheater of Anguish",        5798.49, -3047.38,  307.96, "medium", "ZD_COLISEUM.WMO mesh; the WMO is the whole Gundrak coliseum shell"),
]


def esc(s):
    return s.replace("'", "''")


def header(title, extra=""):
    return """-- %s
--
-- Generated by tools/arenas/gen_arena_sql.py -- edit that, not this.
--
-- Covers the %d arenas ported from the Ascension client data. Map ids are the
-- same ids the source data uses, which is what Tol'viron (980) and Tiger's Peak
-- (1134) already do, so a directory name never has to be reconciled against a
-- map id.
--
-- Apply to lplusdevworld/dbc while iterating; apply to prod when it ships. The
-- dbc.*_lplus mirrors are SHARED between dev and prod -- there is no *_lplusdev
-- flavour -- so these rows reach prod as soon as prod restarts. Every id here is
-- new and unused, so nothing existing is disturbed.
--
-- Replayable: every section deletes its own ids before inserting.
%s
""" % (title, len(ARENAS), extra)


def gen_dbc():
    L = []
    L.append(header("Ported arenas - DBC mirror rows", """--
-- NOTE ON AreaTable: there are deliberately no AreaTable rows here. Map 980
-- (Tol'viron) and 1134 (Tiger's Peak) both carry AreaTableID = 0, and the client
-- works out which area a player is standing in from the area ids baked into the
-- ADTs, not from Map.dbc. A new AreaTable row that no ADT references would
-- therefore never be selected, while still consuming an AreaBit -- and AreaBits
-- are contended right now, with other work in flight on this shared database.
-- The arena scoreboard does not depend on it: the world states are served from
-- C++ before the zone lookup happens (see Player::SendInitWorldStates).
--
-- The binary .dbc files are a SEPARATE source of truth and drift silently if
-- they are not written too -- see tools/arenas/README.md."""))

    L.append("-- Backups, taken once. IF NOT EXISTS keeps a replay from overwriting the")
    L.append("-- original snapshot with already-modified data.")
    for t in ("map", "battlemasterlist", "pvpdifficulty", "worldsafelocs", "worldstateui"):
        L.append("CREATE TABLE IF NOT EXISTS dbc.%s_lplus_bak_arenas AS SELECT * FROM dbc.%s_lplus;" % (t, t))
    L.append("")

    ids = ",".join(str(a[1]) for a in ARENAS)
    bgids = ",".join(str(a[0]) for a in ARENAS)

    # ---------------- Map.dbc
    L.append("-- ---------------------------------------------------------------- Map.dbc")
    L.append("-- Shape copied from map 980: InstanceType 4 (arena), Flags 1, PVP 0,")
    L.append("-- AreaTableID 0, LoadingScreenID 319, MaxPlayers 0.")
    L.append("DELETE FROM dbc.map_lplus WHERE ID IN (%s);" % ids)
    L.append("INSERT INTO dbc.map_lplus")
    L.append("  (ID, Directory, InstanceType, Flags, PVP,")
    L.append("   MapName_Lang_enUS, MapName_Lang_Mask, AreaTableID,")
    L.append("   MapDescription0_Lang_Mask, MapDescription1_Lang_Mask,")
    L.append("   LoadingScreenID, MinimapIconScale, CorpseMapID, CorpseX, CorpseY,")
    L.append("   TimeOfDayOverride, ExpansionID, RaidOffset, MaxPlayers)")
    L.append("VALUES")
    rows = []
    for bg, mid, d, name, cx, cy, cz, conf, ev in ARENAS:
        rows.append("  (%d, '%s', 4, 1, 0, '%s', %d, 0, %d, %d, 319, 0, 0, 0, 0, -1, 0, 0, 0)"
                    % (mid, esc(d), esc(name), LANG_MASK, DESC_MASK, DESC_MASK))
    L.append(",\n".join(rows) + ";")
    L.append("")

    # ---------------- BattlemasterList.dbc
    L.append("-- ---------------------------------------------------- BattlemasterList.dbc")
    L.append("-- ID must equal the BattlegroundTypeId. InstanceType 4 marks it an arena,")
    L.append("-- which is what makes the client offer it in the arena frame rather than")
    L.append("-- the battleground one.")
    L.append("--")
    L.append("-- MapID_2..8 stay -1. Listing several maps in one row is how Blizzard built")
    L.append("-- 'All Arenas' (row 6), and it is exactly the mechanism that caps a random")
    L.append("-- pool at eight, because the column only exists eight times. The random")
    L.append("-- rotation is served from `battleground_random_pool` instead.")
    L.append("DELETE FROM dbc.battlemasterlist_lplus WHERE ID IN (%s);" % bgids)
    L.append("INSERT INTO dbc.battlemasterlist_lplus")
    L.append("  (ID, MapID_1, MapID_2, MapID_3, MapID_4, MapID_5, MapID_6, MapID_7, MapID_8,")
    L.append("   InstanceType, GroupsAllowed, Name_Lang_enUS, Name_Lang_Mask,")
    L.append("   MaxGroupSize, HolidayWorldState, Minlevel, Maxlevel)")
    L.append("VALUES")
    rows = []
    for bg, mid, d, name, cx, cy, cz, conf, ev in ARENAS:
        rows.append("  (%d, %d, -1, -1, -1, -1, -1, -1, -1, 4, 1, '%s', %d, 5, 0, 10, 80)"
                    % (bg, mid, esc(name), LANG_MASK))
    L.append(",\n".join(rows) + ";")
    L.append("")

    # ---------------- PvpDifficulty.dbc
    L.append("-- ------------------------------------------------------- PvpDifficulty.dbc")
    L.append("-- The silent one. Miss these and the queue refuses everyone with no error:")
    L.append("-- GetBattlegroundBracketByLevel simply finds no bracket and fails.")
    L.append("--")
    L.append("-- Sixteen brackets per arena covering levels 10-89, which is what maps 980")
    L.append("-- and 1134 already carry. RangeIndex n spans levels 10+5n .. 14+5n.")
    L.append("DELETE FROM dbc.pvpdifficulty_lplus WHERE MapID IN (%s);" % ids)
    L.append("INSERT INTO dbc.pvpdifficulty_lplus (ID, MapID, RangeIndex, MinLevel, MaxLevel, Difficulty)")
    L.append("VALUES")
    rows = []
    for i, (bg, mid, d, name, cx, cy, cz, conf, ev) in enumerate(ARENAS):
        for r in range(16):
            rows.append("  (%d, %d, %d, %d, %d, 0)" % (
                PVPDIFF_BASE + i * 16 + r, mid, r, 10 + 5 * r, 14 + 5 * r))
    L.append(",\n".join(rows) + ";")
    L.append("")

    # ---------------- WorldSafeLocs.dbc
    L.append("-- ------------------------------------------------------- WorldSafeLocs.dbc")
    L.append("-- Team start positions. These are the coordinates most likely to need a")
    L.append("-- nudge, and they are deliberately here rather than in C++ so that fixing")
    L.append("-- one is an UPDATE and a `.reload battleground_template`.")
    L.append("--")
    L.append("-- Both teams are placed on the X axis either side of the measured centre,")
    L.append("-- %.0f yards out, facing each other -- the same arrangement Tol'viron uses" % SPAWN_OFFSET)
    L.append("-- (its teams sit at X centre +-72 with Y held constant). Z is the measured")
    L.append("-- floor plus %.0f yards so nobody spawns inside the mesh." % SPAWN_Z_LIFT)
    L.append("--")
    L.append("-- Verify each with .gps before considering an arena done; the 'low'")
    L.append("-- confidence ones below are guesses at the structure, not measurements.")
    L.append("DELETE FROM dbc.worldsafelocs_lplus WHERE ID BETWEEN %d AND %d;" % (
        WSL_BASE, WSL_BASE + len(ARENAS) * 2 - 1))
    L.append("INSERT INTO dbc.worldsafelocs_lplus")
    L.append("  (ID, Continent, LocX, LocY, LocZ, AreaName_Lang_enUS, AreaName_Lang_Mask)")
    L.append("VALUES")
    rows = []
    for i, (bg, mid, d, name, cx, cy, cz, conf, ev) in enumerate(ARENAS):
        z = cz + SPAWN_Z_LIFT
        rows.append("  (%d, %d, %.2f, %.2f, %.2f, '%s - Alliance Start', %d),   -- confidence: %s"
                    % (WSL_BASE + i * 2, mid, cx + SPAWN_OFFSET, cy, z, esc(name), LANG_MASK, conf))
        rows.append("  (%d, %d, %.2f, %.2f, %.2f, '%s - Horde Start',    %d)"
                    % (WSL_BASE + i * 2 + 1, mid, cx - SPAWN_OFFSET, cy, z, esc(name), LANG_MASK))
    L.append(",\n".join(rows) + ";")
    L.append("")

    # ---------------- WorldStateUI.dbc
    L.append("-- -------------------------------------------------------- WorldStateUI.dbc")
    L.append("-- The 'N players remaining' readout above the arena frame.")
    L.append("--")
    L.append("-- Two rows per arena, which is exactly what every existing arena carries")
    L.append("-- (maps 559, 562, 572, 617, 618, 980 and 1134 all have precisely two).")
    L.append("-- Shape copied verbatim from Tiger's Peak's pair, 90006/90007.")
    L.append("--")
    L.append("-- %3600w and %3601w substitute the live values of the two alive-player")
    L.append("-- world states; StateVariable 3610 is the flag that decides whether the")
    L.append("-- pair is drawn at all. The server sends all three -- 3610 from")
    L.append("-- BattlegroundCustomArena::FillInitialWorldStates, 3600/3601 from")
    L.append("-- Arena::UpdateArenaWorldState -- so without these rows the client receives")
    L.append("-- the numbers and stores them but has nothing declared to display them.")
    L.append("--")
    L.append("-- AreaID 0 means 'anywhere on this map', which matters because these arenas")
    L.append("-- report whatever zone id their source ADTs baked in rather than a zone of")
    L.append("-- their own.")
    L.append("--")
    L.append("-- CLIENT-side: no effect until packed into the client patch.")
    L.append("DELETE FROM dbc.worldstateui_lplus WHERE ID BETWEEN %d AND %d;" % (
        WSUI_BASE, WSUI_BASE + len(ARENAS) * 2 - 1))
    L.append("INSERT INTO dbc.worldstateui_lplus")
    L.append("  (ID, MapID, AreaID, PhaseShift, Icon,")
    L.append("   String_Lang_enUS, String_Lang_Mask, Tooltip_Lang_Mask,")
    L.append("   StateVariable, Type, DynamicIcon, DynamicTooltip_Lang_Mask,")
    L.append("   ExtendedUI, ExtendedUIStateVariable_1, ExtendedUIStateVariable_2, ExtendedUIStateVariable_3)")
    L.append("VALUES")
    rows = []
    for i, (bg, mid, d, name, cx, cy, cz, conf, ev) in enumerate(ARENAS):
        rows.append("  (%d, %d, 0, 0, '', 'Green Team: %%3600w Players Remaining', %d, %d, 3610, 0, '', %d, '', 0, 0, 0)"
                    % (WSUI_BASE + i * 2, mid, LANG_MASK, DESC_MASK, DESC_MASK))
        rows.append("  (%d, %d, 0, 0, '', 'Gold Team: %%3601w Players Remaining',  %d, %d, 3610, 0, '', %d, '', 0, 0, 0)"
                    % (WSUI_BASE + i * 2 + 1, mid, LANG_MASK, DESC_MASK, DESC_MASK))
    L.append(",\n".join(rows) + ";")
    L.append("")

    return "\n".join(L)


def gen_world():
    L = []
    L.append(header("Ported arenas - world DB", """--
-- Pairs with:
--   sql/custom/dbc/%s_dbc_ported_arenas.sql
--   src/server/game/Battlegrounds/Zones/BattlegroundCustomArena.{h,cpp}
--
-- Creates two new tables. Both are read by BattlegroundMgr::LoadBattlegroundTemplates,
-- so `.reload battleground_template` picks up edits to either without a restart.""" % STAMP))

    # ---------------- battleground_template
    L.append("-- --------------------------------------------------- battleground_template")
    L.append("-- MinPlayersPerTeam 0 / MaxPlayersPerTeam 5 matches Tol'viron. The real cap")
    L.append("-- comes from the arena type at creation time (2v2/3v3/4v4/5v5), which")
    L.append("-- BattlegroundMgr::CreateNewBattleground applies after the template is copied.")
    L.append("--")
    L.append("-- StartMaxDist 0 disables the leash, as every other arena here does.")
    L.append("-- Weight is only consulted for random selection, and the arena rotation now")
    L.append("-- comes from battleground_random_pool below, so it is left at 1.")
    L.append("DELETE FROM battleground_template WHERE ID BETWEEN %d AND %d;" % (
        ARENAS[0][0], ARENAS[-1][0]))
    L.append("INSERT INTO battleground_template")
    L.append("  (ID, MinPlayersPerTeam, MaxPlayersPerTeam, MinLvl, MaxLvl,")
    L.append("   AllianceStartLoc, AllianceStartO, HordeStartLoc, HordeStartO,")
    L.append("   StartMaxDist, Weight, ScriptName, Comment)")
    L.append("VALUES")
    rows = []
    for i, (bg, mid, d, name, cx, cy, cz, conf, ev) in enumerate(ARENAS):
        rows.append("  (%d, 0, 5, 10, 80, %d, 3.14159, %d, 0, 0, 1, '', '%s')"
                    % (bg, WSL_BASE + i * 2, WSL_BASE + i * 2 + 1, esc(name)))
    L.append(",\n".join(rows) + ";")
    L.append("")

    # ---------------- random pool
    L.append("-- ------------------------------------------------ battleground_random_pool")
    L.append("-- Replaces the eight-map ceiling on random selection.")
    L.append("--")
    L.append("-- BattlegroundMgr::GetRandomBG used to build its candidate list from")
    L.append("-- BattlemasterListEntry::MapID, which is a fixed `int32 MapID[8]` in the")
    L.append("-- client's DBC format. 'All Arenas' therefore could not roll a ninth arena")
    L.append("-- however many were installed -- and on this realm it was rolling only two,")
    L.append("-- because row 6 listed just Nagrand and Blade's Edge.")
    L.append("--")
    L.append("-- This table has no such limit and needs no DBC edit: change a row, run")
    L.append("-- `.reload battleground_template`, and the next queue pop uses it.")
    L.append("--")
    L.append("--   PoolBgTypeId   what the player queued for: 6 = All Arenas,")
    L.append("--                  32 = Random Battleground")
    L.append("--   MemberBgTypeId a candidate to roll")
    L.append("--   Weight         relative likelihood, any positive value")
    L.append("--   Enabled        0 takes an arena out of rotation without deleting the row")
    L.append("DROP TABLE IF EXISTS `battleground_random_pool`;")
    L.append("CREATE TABLE `battleground_random_pool` (")
    L.append("  `PoolBgTypeId`   int unsigned NOT NULL COMMENT 'BattlegroundTypeId players queue for (6=All Arenas, 32=Random BG)',")
    L.append("  `MemberBgTypeId` int unsigned NOT NULL COMMENT 'BattlegroundTypeId that may be rolled',")
    L.append("  `Weight`         double NOT NULL DEFAULT '1' COMMENT 'Relative selection weight; must be > 0',")
    L.append("  `Enabled`        tinyint unsigned NOT NULL DEFAULT '1' COMMENT '0 disables without deleting',")
    L.append("  `Comment`        varchar(64) NOT NULL DEFAULT '',")
    L.append("  PRIMARY KEY (`PoolBgTypeId`,`MemberBgTypeId`)")
    L.append(") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Random battleground/arena selection pools';")
    L.append("")
    L.append("-- All Arenas (6): the five stock arenas plus every ported one. Sixteen")
    L.append("-- entries -- twice what the DBC route could ever have expressed.")
    L.append("INSERT INTO `battleground_random_pool` (PoolBgTypeId, MemberBgTypeId, Weight, Enabled, Comment) VALUES")
    pool = [
        (4,  "Nagrand Arena"), (5, "Blade's Edge Arena"), (8, "Ruins of Lordaeron"),
        (10, "Dalaran Sewers"), (11, "The Ring of Valor"),
        (103, "Nefarian's Arena"), (870, "Tol'Viron Arena"), (871, "The Tiger's Peak"),
    ]
    rows = ["  (6, %d, 1, 1, '%s')" % (m, esc(c)) for m, c in pool]
    for bg, mid, d, name, cx, cy, cz, conf, ev in ARENAS:
        rows.append("  (6, %d, 1, 1, '%s')" % (bg, esc(name[:60])))
    L.append(",\n".join(rows) + ";")
    L.append("")

    # ---------------- arena objects
    L.append("-- ------------------------------------------ battleground_custom_arena_object")
    L.append("-- Gates and buffs for the data-driven arenas, spawned by")
    L.append("-- BattlegroundCustomArena::SetupBattleground.")
    L.append("--")
    L.append("--   ObjectType 0 = door   spawned closed, opened on the start countdown")
    L.append("--   ObjectType 1 = buff   shadowsight nodes, spawned 60s after the gates open")
    L.append("--")
    L.append("-- NO BUFF ROWS ARE SEEDED. Shadowsight positions have to be eyeballed in-game")
    L.append("-- and are being left for later; an arena with no buff rows simply has no")
    L.append("-- buffs and is otherwise fully playable. Add them with:")
    L.append("--")
    L.append("--   INSERT INTO battleground_custom_arena_object")
    L.append("--     (BgTypeId, GoEntry, X, Y, Z, Orientation, Rotation0, Rotation1, Rotation2, Rotation3, ObjectType, Comment)")
    L.append("--   VALUES (872, 184663, <x>, <y>, <z>, <o>, 0, 0, 0, 1, 1, 'shadowsight');")
    L.append("--")
    L.append("-- then `.reload battleground_template`. GameObject 184663/184664 are the two")
    L.append("-- Shadow Sight nodes; 179469 below is the stock 'Arena Door'.")
    L.append("--")
    L.append("-- The gate positions are derived, not surveyed: %.0f yards either side of the" % DOOR_OFFSET)
    L.append("-- measured centre on the X axis, with the team spawns %.0f yards out so players" % SPAWN_OFFSET)
    L.append("-- start behind their own gate. Expect to adjust these.")
    L.append("DROP TABLE IF EXISTS `battleground_custom_arena_object`;")
    L.append("CREATE TABLE `battleground_custom_arena_object` (")
    L.append("  `Id`          int unsigned NOT NULL AUTO_INCREMENT,")
    L.append("  `BgTypeId`    int unsigned NOT NULL COMMENT 'BattlegroundTypeId, must be a data-driven arena',")
    L.append("  `GoEntry`     int unsigned NOT NULL COMMENT 'gameobject_template.entry',")
    L.append("  `X`           float NOT NULL DEFAULT '0',")
    L.append("  `Y`           float NOT NULL DEFAULT '0',")
    L.append("  `Z`           float NOT NULL DEFAULT '0',")
    L.append("  `Orientation` float NOT NULL DEFAULT '0',")
    L.append("  `Rotation0`   float NOT NULL DEFAULT '0',")
    L.append("  `Rotation1`   float NOT NULL DEFAULT '0',")
    L.append("  `Rotation2`   float NOT NULL DEFAULT '0',")
    L.append("  `Rotation3`   float NOT NULL DEFAULT '1',")
    L.append("  `ObjectType`  tinyint unsigned NOT NULL DEFAULT '0' COMMENT '0=door, 1=buff',")
    L.append("  `Comment`     varchar(64) NOT NULL DEFAULT '',")
    L.append("  PRIMARY KEY (`Id`),")
    L.append("  KEY `idx_bgtype` (`BgTypeId`,`ObjectType`)")
    L.append(") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Gates and buffs for data-driven custom arenas';")
    L.append("")
    L.append("INSERT INTO `battleground_custom_arena_object`")
    L.append("  (BgTypeId, GoEntry, X, Y, Z, Orientation, Rotation0, Rotation1, Rotation2, Rotation3, ObjectType, Comment)")
    L.append("VALUES")
    rows = []
    for bg, mid, d, name, cx, cy, cz, conf, ev in ARENAS:
        rows.append("  (%d, %d, %.2f, %.2f, %.2f, 3.14159, 0, 0, 1, 0, 0, '%s gate A')"
                    % (bg, DOOR_GO, cx + DOOR_OFFSET, cy, cz, esc(d[:40])))
        rows.append("  (%d, %d, %.2f, %.2f, %.2f, 0, 0, 0, 0, 1, 0, '%s gate H')"
                    % (bg, DOOR_GO, cx - DOOR_OFFSET, cy, cz, esc(d[:40])))
    L.append(",\n".join(rows) + ";")
    L.append("")

    # ---------------- provenance
    L.append("-- ------------------------------------------------------------- provenance")
    L.append("-- How each centre was established, and how much to trust it:")
    L.append("--")
    for bg, mid, d, name, cx, cy, cz, conf, ev in ARENAS:
        L.append("--   %-4d %-20s %-7s %s" % (bg, d[:20], conf, ev))
    L.append("")

    return "\n".join(L)


def main():
    dbc_path = os.path.join(OUT_DBC, "%s_dbc_ported_arenas.sql" % STAMP)
    world_path = os.path.join(OUT_WORLD, "%s_world_ported_arenas.sql" % STAMP)
    with open(dbc_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(gen_dbc())
    with open(world_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(gen_world())
    print("wrote %s" % dbc_path)
    print("wrote %s" % world_path)
    print("%d arenas, %d pvpdifficulty rows, %d worldsafelocs, %d worldstateui, %d gates" % (
        len(ARENAS), len(ARENAS) * 16, len(ARENAS) * 2, len(ARENAS) * 2, len(ARENAS) * 2))


if __name__ == "__main__":
    main()
