"""What still needs walking in-game, and what is already surveyed.

Gate and shadowsight positions cannot be derived from anything: no DBC lists
them, and the terrain does not say where a doorway is. Team starts came from
Ascension's WorldSafeLocs.dbc, but gates and buffs have to be measured.

Everything a derived arena is using today is a placeholder -- the gates sit 85%
of the way from the arena centre to each team start, which is what the surveyed
arenas actually measure, so they land in roughly the right doorway but not on it.
Arenas with no buff rows have no shadowsight nodes at all.

Reads MEASURED and DISABLED out of gen_arena_sql.py, so it cannot drift from
what is actually generated.

Usage:
    python survey_status.py            # print the table
    python survey_status.py --write    # also refresh SURVEY.md
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from gen_arena_sql import (ARENAS, DISABLED, MEASURED, gates_for,  # noqa: E402
                           measured, start_positions)


def rows():
    out = []
    for bg, mid, directory, name, cx, cy, cz, conf, ev in ARENAS:
        m = measured(bg) or {}
        out.append({
            "bg": bg,
            "map": mid,
            "dir": directory,
            "name": name,
            "held": bg in DISABLED,
            "gates": bool(m.get("gates")),
            "buffs": len(m.get("buffs", [])),
            "starts": "Ascension DBC" if m.get("alliance") else "derived",
            "gate_pos": gates_for(bg, cx, cy, cz),
            "start_pos": start_positions(bg, cx, cy, cz),
        })
    return out


def table(rs, held):
    want = [r for r in rs if r["held"] == held]
    lines = []
    hdr = "| BG | Map | Directory | Arena | Gates | Shadowsight |"
    lines.append(hdr)
    lines.append("|---|---|---|---|---|---|")
    for r in sorted(want, key=lambda r: r["bg"]):
        g = "surveyed" if r["gates"] else "**needed**"
        b = ("surveyed (%d)" % r["buffs"]) if r["buffs"] else "**needed**"
        lines.append("| %d | %d | `%s` | %s | %s | %s |"
                     % (r["bg"], r["map"], r["dir"], r["name"], g, b))
    return lines


def where_to_look(rs):
    lines = []
    lines.append("| Map | Arena | Go here (placeholder gate positions) |")
    lines.append("|---|---|---|")
    for r in sorted((x for x in rs if not x["held"] and not x["gates"]),
                    key=lambda r: r["map"]):
        g1, g2 = r["gate_pos"][0], r["gate_pos"][1]
        lines.append("| %d | %s | `.go xyz %.1f %.1f %.1f %d` &nbsp;/&nbsp; `.go xyz %.1f %.1f %.1f %d` |"
                     % (r["map"], r["name"], g1[1], g1[2], g1[3], r["map"],
                        g2[1], g2[2], g2[3], r["map"]))
    return lines


def main():
    rs = rows()
    live = [r for r in rs if not r["held"]]
    done = [r for r in live if r["gates"] and r["buffs"]]

    body = []
    body.append("# Arena survey status")
    body.append("")
    body.append("Generated by `tools/arenas/survey_status.py` — re-run it, don't hand-edit.")
    body.append("")
    body.append("**%d of %d enabled arenas fully surveyed.** Team starts are already correct"
                % (len(done), len(live)))
    body.append("everywhere (they come from Ascension's own `WorldSafeLocs.dbc`); what is")
    body.append("missing is gates and shadowsight, which exist in no data source and have to")
    body.append("be measured in-game.")
    body.append("")
    body.append("## Enabled")
    body.append("")
    body.extend(table(rs, held=False))
    body.append("")
    body.append("## Held back")
    body.append("")
    body.append("Disabled in `disables` (sourceType 3). Not needed until they are re-enabled.")
    body.append("")
    body.extend(table(rs, held=True))
    body.append("")
    body.append("## Where to stand")
    body.append("")
    body.append("The placeholder gates are 85% of the way from the arena centre to each team")
    body.append("start — the ratio the surveyed arenas actually measure — so these land in")
    body.append("roughly the right doorway. Teleport there, then `.gps` the real spot.")
    body.append("")
    body.extend(where_to_look(rs))
    body.append("")
    body.append("## How to send a survey")
    body.append("")
    body.append("For each arena, two gates and two shadowsight nodes:")
    body.append("")
    body.append("```")
    body.append(".gobject add 185483        # at each gate, then .gobject near for the guid")
    body.append(".gps                       # standing on each shadowsight spot")
    body.append("```")
    body.append("")
    body.append("Gate rotations are read from the `gameobject` rows, so the guids are enough —")
    body.append("`.gobject add` does not print orientation. If a gate is nudged after placing,")
    body.append("the DB position wins, not the one the add command echoed.")
    body.append("")
    body.append("## Where the numbers live")
    body.append("")
    body.append("| Stage | Location |")
    body.append("|---|---|")
    body.append("| Source of truth | `tools/arenas/gen_arena_sql.py` → `MEASURED` |")
    body.append("| Generated SQL | `sql/custom/world/2026_08_06_02_world_ported_arenas.sql` |")
    body.append("| Applied to | `lplusdevworld.battleground_custom_arena_object` |")
    body.append("| Read at runtime | `BattlegroundCustomArena::LoadObjects()` |")
    body.append("")
    body.append("No coordinate is compiled into the C++. Adding a survey is an edit to")
    body.append("`MEASURED`, a regenerate, an apply, and `.reload battleground_template` —")
    body.append("never a rebuild.")
    body.append("")

    text = "\n".join(body)
    print(text)

    if "--write" in sys.argv:
        dest = os.path.join(HERE, "SURVEY.md")
        with open(dest, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        print("\nwrote %s" % dest)


if __name__ == "__main__":
    main()
