#!/usr/bin/env python3
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]
REF_MODULE = ROOT / "playerbot reference" / "mod-playerbots-master"
REF_CORE = ROOT / "playerbot reference" / "azerothcore-wotlk-Playerbot"
OUT_FILE = ROOT / "doc" / "playerbot" / "pvp-scope-inventory.md"

KEYWORDS = (
    "pvp",
    "battleground",
    "battle ground",
    "arena",
    "duel",
    "flag",
    "bg",
)

EXTS = {".h", ".hpp", ".cpp", ".cc", ".c", ".inl", ".inc", ".txt", ".md", ".dist", ".sql", ".cmake", ""}


def interesting(path: Path) -> bool:
    if "/.git/" in str(path):
        return False
    if "build" in path.parts:
        return False
    if path.is_dir():
        return False
    if path.suffix.lower() not in EXTS and path.name not in {"CMakeLists.txt"}:
        return False
    return True


def scan(base: Path):
    matches = []
    for p in base.rglob("*"):
        if not interesting(p):
            continue
        rel = p.relative_to(base)
        text = ""
        try:
            text = p.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue

        lines = text.splitlines()
        hit_lines = []
        for i, line in enumerate(lines, start=1):
            lower = line.lower()
            if any(k in lower for k in KEYWORDS):
                # exclude obvious false positives like debug abbreviations
                if re.search(r"\b(debug|dbg)\b", lower):
                    continue
                hit_lines.append(i)

        if hit_lines:
            matches.append((str(rel), len(hit_lines), hit_lines[:8]))

    matches.sort(key=lambda x: (-x[1], x[0]))
    return matches


def render(module_hits, core_hits):
    lines = []
    lines.append("# Playerbot PvP Scope Inventory")
    lines.append("")
    lines.append("Generated by `tools/playerbot/extract_pvp_scope.py`.")
    lines.append("")
    lines.append("## Reference module files (`mod-playerbots-master`)")
    lines.append("")
    for path, count, sample in module_hits[:200]:
        lines.append(f"- `{path}` — {count} keyword hits (sample lines: {', '.join(map(str, sample))})")

    lines.append("")
    lines.append("## Reference core files (`azerothcore-wotlk-Playerbot`)")
    lines.append("")
    for path, count, sample in core_hits[:200]:
        lines.append(f"- `{path}` — {count} keyword hits (sample lines: {', '.join(map(str, sample))})")

    lines.append("")
    lines.append("## Notes")
    lines.append("")
    lines.append("- This is a broad keyword inventory to drive porting order.")
    lines.append("- Next step is classifying these files into: AI logic, strategy/triggers, battleground/arena queueing, and core hooks.")
    return "\n".join(lines) + "\n"


def main():
    module_hits = scan(REF_MODULE)
    core_hits = scan(REF_CORE)
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(render(module_hits, core_hits), encoding="utf-8")
    print(f"Wrote {OUT_FILE}")
    print(f"Module hits: {len(module_hits)}")
    print(f"Core hits: {len(core_hits)}")


if __name__ == "__main__":
    main()
