"""Phase 3 world-DB rows for Blood Beneath the Arena (the encounter scripts).

Writes bba_phase3.sql / bba_phase3_rollback.sql next to this file. Same fresh id ranges as
gen_bba_sql.py; apply AFTER bba_content.sql, with `USE <db>;` prepended.

  - ScriptNames for every scripted NPC / object, instance_template.script
  - four helper templates: Bloodbound Zealot 922072, Nerubian Spiderling 922073,
    Blood Web Cocoon 922074, the ground-effect trigger 922080 (level 61, so its spells do not
    miss level-60 players on level difference)
  - the tribal champions, supports and wave trash are no longer static spawns: the gong
    summons them, so their copied mock-up spawns are removed from map 1685
  - Vraka'ti's gossip + her offering chest (900302), the extra gossip texts, her betrayal line
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
MAP = 1685


def q(s):
    return "'" + str(s).replace('\\', '\\\\').replace("'", "\\'") + "'"


SCRIPTS = {
    'npc_bba_varjun': [922000],
    'npc_bba_blightblood': [922001],
    'npc_bba_champion': [922010, 922020, 922030],
    'npc_bba_support': [922011, 922021, 922031],
    'npc_bba_trash': [922012, 922013, 922014, 922022, 922023, 922024, 922032, 922033, 922034,
                      922040, 922041, 922042, 922043, 922044, 922045, 922046, 922072, 922073],
    'boss_bba_zalvaxa': [922050],
    'npc_bba_risen': [922051],
    'boss_bba_twin': [922060, 922061],
    'boss_bba_vrakati': [922070],
    'boss_bba_anoksuten': [922071],
    'npc_bba_cocoon': [922074],
    'npc_bba_zone': [922080],
}
TRIAL_ENTRIES = [922010, 922011, 922012, 922013, 922014, 922020, 922021, 922022, 922023, 922024,
                 922030, 922031, 922032, 922033, 922034]

TEXTS = {
    60106: "So the arena sends champions below the floor. How generous.$B$BYou have proven yourselves. Take the offering beside my throne and leave this place with your lives. Or stay, and feed the cauldron.",
    60107: "Bang the gong when your minds are clear and your mana is full. Once it rings, the cult will know we are here.$B$BSand, then ice, then forest. Break each tribe's champion and the pillar will run clean.",
    60108: "The pillar is clean. Something underneath it is not. I can feel it.$B$BZalvaxa's dead still walk. Let me call her out - and when she starts her ritual, break it. Kick, silence, stun, anything.",
    60109: "Good. They expected frightened prisoners, not five armed problems.$B$BClear the patrols between here and the cauldrons, then tell me when you are ready. I will lead you to the pillar.",
    60110: "The Bloodbound stole these gifts from the blood of their captives. Take them back. They were never theirs.",
    60111: "No more drums. No more bones. Upstairs, quickly. The arena is becoming a coffin.",
    60112: "You did not save the arena. You saved the people beneath it. Remember the difference.",
}

OFFERING_POS = (-13214.0, 283.5, -58.2, 0.22)


def build():
    o = []
    w = o.append
    w("-- Blood Beneath the Arena - phase 3 rows (generated by gen_bba_phase3_sql.py)")
    w("START TRANSACTION;")
    w(open(os.path.join(HERE, 'bba_phase3_rollback_body.sql')).read())

    # helper templates
    w("DROP TEMPORARY TABLE IF EXISTS bba_ct3; CREATE TEMPORARY TABLE bba_ct3 LIKE creature_template;")
    w("INSERT INTO bba_ct3 SELECT * FROM creature_template WHERE entry=922040;")
    w("UPDATE bba_ct3 SET entry=922072, name='Bloodbound Zealot', mingold=0, maxgold=0 WHERE entry=922040;")
    w("INSERT INTO bba_ct3 SELECT * FROM creature_template WHERE entry=15041;")
    w("UPDATE bba_ct3 SET entry=922073, name='Nerubian Spiderling', subname=NULL, minlevel=60, maxlevel=60, exp=0, faction=14, `rank`=0, "
      "unit_class=1, unit_flags=0, npcflag=0, lootid=0, mingold=0, maxgold=0, AIName='', ScriptName='', HealthModifier=0.3, DamageModifier=1.2, "
      "BaseAttackTime=1500, VerifiedBuild=0 WHERE entry=15041;")
    w("INSERT INTO bba_ct3 SELECT * FROM creature_template WHERE entry=38028;")
    w("UPDATE bba_ct3 SET entry=922074, name='Blood Web Cocoon', subname=NULL, minlevel=60, maxlevel=60, exp=0, faction=14, `rank`=0, "
      "unit_class=1, unit_flags=0, npcflag=0, lootid=0, mingold=0, maxgold=0, AIName='', ScriptName='', HealthModifier=1.0, DamageModifier=0, "
      "mechanic_immune_mask=0, flags_extra=0, VerifiedBuild=0 WHERE entry=38028;")
    w("INSERT INTO bba_ct3 SELECT * FROM creature_template WHERE entry=15384;")
    w("UPDATE bba_ct3 SET entry=922080, name='Blood Ritual Trigger', subname=NULL, minlevel=61, maxlevel=61, exp=0, faction=14, `rank`=0, "
      "npcflag=0, lootid=0, mingold=0, maxgold=0, AIName='', ScriptName='', VerifiedBuild=0 WHERE entry=15384;")
    w("INSERT INTO creature_template SELECT * FROM bba_ct3;")
    w("UPDATE creature_template ct JOIN creature_classlevelstats s ON s.level=ct.minlevel AND s.class=ct.unit_class "
      "SET ct.HealthModifier=ROUND(3000/s.basehp0,3) WHERE ct.entry=922074;")
    w("DELETE FROM creature_template_movement WHERE CreatureId BETWEEN 922072 AND 922080;")
    w("INSERT INTO creature_template_movement (CreatureId,Ground,Swim,Flight,Rooted,Chase,Random,InteractionPauseTimer) "
      "SELECT 922072,Ground,Swim,Flight,Rooted,Chase,Random,InteractionPauseTimer FROM creature_template_movement WHERE CreatureId=922040;")
    w("INSERT INTO creature_equip_template (CreatureID,ID,ItemID1,ItemID2,ItemID3,VerifiedBuild) "
      "SELECT 922072,ID,ItemID1,ItemID2,ItemID3,0 FROM creature_equip_template WHERE CreatureID=922040;")

    # script names
    for script, entries in SCRIPTS.items():
        w("UPDATE creature_template SET ScriptName=%s, AIName='' WHERE entry IN (%s);" % (q(script), ','.join(map(str, entries))))
    w("UPDATE creature_template SET npcflag=1, gossip_menu_id=60106 WHERE entry=922070;")
    w("UPDATE gameobject_template SET ScriptName='go_bba_gong' WHERE entry=900300;")
    w("UPDATE instance_template SET script='instance_blood_beneath_arena' WHERE map=%d;" % MAP)

    # the trials are summoned by the gong now
    w("DELETE FROM creature WHERE map=%d AND id IN (%s);" % (MAP, ','.join(map(str, TRIAL_ENTRIES))))

    # gossip text: the script builds the menus; the DB options from phase 2 are superseded
    w("DELETE FROM gossip_menu_option WHERE MenuID IN (60100,60102);")
    for tid, text in TEXTS.items():
        w("INSERT INTO npc_text (ID,text0_0,text0_1,BroadcastTextID0,lang0,Probability0,VerifiedBuild) VALUES (%d,%s,%s,0,0,1,0);" % (tid, q(text), q(text)))
    w("INSERT INTO gossip_menu (MenuID,TextID,VerifiedBuild) VALUES (60106,60106,0);")

    # Vraka'ti's betrayal line
    w("INSERT INTO creature_text (CreatureID,GroupID,ID,Text,Type,Language,Probability,Emote,Duration,Sound,BroadcastTextId,TextRange,comment) VALUES "
      "(922070,8,0,%s,14,0,100,0,0,0,0,0,'BBA 922070 - offering taken');" % q("Take it, then, and crawl back to your arena. The blood has no use for cowards."))

    # the offering beside the throne
    w("DROP TEMPORARY TABLE IF EXISTS bba_gt3; CREATE TEMPORARY TABLE bba_gt3 LIKE gameobject_template;")
    w("INSERT INTO bba_gt3 SELECT * FROM gameobject_template WHERE entry=179697;")
    w("UPDATE bba_gt3 SET entry=900302, type=10, name=%s, Data0=0, Data1=0, Data2=0, Data3=0, Data4=0, Data5=0, Data6=0, Data7=0, "
      "Data8=0, Data9=0, Data10=0, Data11=0, Data12=0, Data13=0, Data14=0, Data15=0, AIName='', ScriptName='go_bba_offering', VerifiedBuild=0 "
      "WHERE entry=179697;" % q("Vraka'ti's Offering"))
    w("INSERT INTO gameobject_template SELECT * FROM bba_gt3;")
    w("DROP TEMPORARY TABLE IF EXISTS bba_go3; CREATE TEMPORARY TABLE bba_go3 LIKE gameobject;")
    w("INSERT INTO bba_go3 SELECT * FROM gameobject WHERE guid=5331000;")   # the gong copy, as a row template
    x, y, z, ori = OFFERING_POS
    w("UPDATE bba_go3 SET guid=5331190, id=900302, position_x=%s, position_y=%s, position_z=%s, orientation=%s, "
      "rotation0=0, rotation1=0, rotation2=SIN(%s/2), rotation3=COS(%s/2), spawntimesecs=86400;" % (x, y, z, ori, ori, ori))
    w("INSERT INTO gameobject SELECT * FROM bba_go3;")
    w("COMMIT;")
    return '\n'.join(o) + '\n'


ROLLBACK = """-- undo phase 3 rows (phase 2 rows stay)
DELETE FROM creature_template WHERE entry IN (922072,922073,922074,922080);
DELETE FROM creature_template_movement WHERE CreatureId IN (922072,922073,922074,922080);
DELETE FROM creature_equip_template WHERE CreatureID IN (922072,922073,922074,922080);
DELETE FROM npc_text WHERE ID BETWEEN 60106 AND 60112;
DELETE FROM gossip_menu WHERE MenuID=60106;
DELETE FROM creature_text WHERE CreatureID=922070 AND GroupID=8;
DELETE FROM gameobject WHERE guid=5331190;
DELETE FROM gameobject_template WHERE entry=900302;
"""

if __name__ == '__main__':
    open(os.path.join(HERE, 'bba_phase3_rollback_body.sql'), 'w', newline='\n').write(ROLLBACK)
    open(os.path.join(HERE, 'bba_phase3_rollback.sql'), 'w', newline='\n').write(
        ROLLBACK + "-- and to fully revert scripts: UPDATE creature_template SET ScriptName='' WHERE entry BETWEEN 922000 AND 922099;\n"
        "-- trial spawns removed by phase 3 come back by re-running bba_content.sql\n")
    sql = build()
    open(os.path.join(HERE, 'bba_phase3.sql'), 'w', newline='\n', encoding='utf-8').write(sql)
    print('bba_phase3.sql: %d lines' % sql.count('\n'))
